return {
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        -- Web and data formats
        vue = { "prettier" },
        scss = { "prettier" },
        css = { "prettier" },
        less = { "prettier" },
        html = { "prettier" },
        htmlangular = { "prettier" },
        javascript = { "prettier" },
        javascriptreact = { "prettier" },
        typescript = { "prettier" },
        typescriptreact = { "prettier" },
        json = { "prettier" },
        jsonc = { "prettier" },
        json5 = { "prettier" },
        yaml = { "prettier" },
        graphql = { "prettier" },
        handlebars = { "prettier" },
        svelte = { "prettier" },
        astro = { "prettier" },
        markdown = { "prettier" },
        mdx = { "prettier" },
        ["markdown.mdx"] = { "prettier" },

        -- C-family and systems languages
        c = { "clang-format" },
        cpp = { "clang-format" },
        objc = { "clang-format" },
        objcpp = { "clang-format" },
        cuda = { "clang-format" },
        proto = { "clang-format" },
        rust = { "rustfmt" },
        go = { "goimports", "gofumpt" },
        zig = { "zigfmt" },
        v = { "v" },

        -- JVM and application languages
        kotlin = { "ktlint" },
        java = { "google-java-format" },
        scala = { "scalafmt" },
        dart = { "dart_format" },
        python = { "ruff_format" },
        ruby = { "rubocop" },
        php = { "php_cs_fixer" },
        cs = { "csharpier" },
        swift = { "swift_format" },

        -- Shell, config, and build files
        lua = { "stylua" },
        bash = { "shfmt" },
        sh = { "shfmt" },
        zsh = { "shfmt" },
        fish = { "fish_indent" },
        toml = { "taplo" },
        xml = { "xmllint" },
        sql = { "sql_formatter" },
        cmake = { "cmake_format" },
        dockerfile = { "dockerfmt" },
        nix = { "nixfmt" },
        terraform = { "terraform_fmt" },
        hcl = { "hcl" },
        kdl = { "kdlfmt" },

        -- Additional common language ecosystems
        elixir = { "mix" },
        erlang = { "erlfmt" },
        clojure = { "cljfmt" },
        haskell = { "ormolu" },
        ocaml = { "ocamlformat" },
        nim = { "nimpretty" },
        elm = { "elm_format" },
        gleam = { "gleam" },
        racket = { "racketfmt" },
        julia = { "runic" },
        r = { "styler" },
        perl = { "perltidy" },
        rst = { "rstfmt" },
        typst = { "typstyle" },
        tex = { "tex-fmt" },
        plaintex = { "tex-fmt" },
      },

      default_format_opts = {
        timeout_ms = 3000,
        lsp_format = "fallback",
      },
    },
  },
}
